# Missing Indicator Imputation
This method create a separate new columns with True & False boolean values which indicates that weither there is missing values, so it denote by True other wise False

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import MissingIndicator,SimpleImputer

In [2]:
df = pd.read_csv('/home/saad/Downloads/tested.csv',usecols=['Age','Fare','Survived'])

In [3]:
df['Fare'].fillna(df['Fare'].median(), inplace=True)

In [4]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [5]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [6]:
X_train.head()

Age     Fare
336  32.0  13.0000
31   24.0  31.5000
84    NaN  10.7083
287  24.0  82.2667
317  19.0  10.5000

In [7]:
si = SimpleImputer()
X_train_trf = si.fit_transform(X_train)
X_test_trf = si.transform(X_test)

In [8]:
X_train_trf

array([[3.20000000e+01, 1.30000000e+01],
       [2.40000000e+01, 3.15000000e+01],
       [3.01157634e+01, 1.07083000e+01],
       [2.40000000e+01, 8.22667000e+01],
       [1.90000000e+01, 1.05000000e+01],
       [3.01157634e+01, 7.05000000e+00],
       [2.50000000e+01, 2.60000000e+01],
       [6.00000000e+00, 2.10750000e+01],
       [4.60000000e+01, 7.92000000e+01],
       [1.40000000e+01, 9.22500000e+00],
       [2.50000000e+01, 7.92500000e+00],
       [1.00000000e+01, 4.69000000e+01],
       [3.10000000e+01, 1.80000000e+01],
       [1.70000000e+01, 4.71000000e+01],
       [3.01157634e+01, 7.75000000e+00],
       [3.50000000e+01, 1.23500000e+01],
       [2.40000000e+01, 7.77500000e+00],
       [3.01157634e+01, 7.75000000e+00],
       [2.30000000e+01, 7.05000000e+00],
       [2.70000000e+01, 8.66250000e+00],
       [2.70000000e+01, 7.92500000e+00],
       [3.01157634e+01, 2.54667000e+01],
       [1.70000000e+01, 7.89580000e+00],
       [2.30000000e+01, 1.05000000e+01],
       [3.011576

In [9]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf,y_train)

y_pred = clf.predict(X_test_trf)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6071428571428571

## Missing Indicator

In [10]:
mi = MissingIndicator()

In [11]:
mi.fit(X_train)

MissingIndicator()

In [12]:
X_train_missing = mi.transform(X_train)

In [13]:
mi.features_

array([0])

In [14]:
X_train_missing

array([[False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [

In [15]:
X_test_missing = mi.transform(X_test)

In [16]:
X_test_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [17]:
X_train['Age_NA'] = X_train_missing

<ipython-input-17-453d4a172d2f>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['Age_NA'] = X_train_missing


In [18]:
X_train

Age     Fare  Age_NA
336  32.0  13.0000   False
31   24.0  31.5000   False
84    NaN  10.7083    True
287  24.0  82.2667   False
317  19.0  10.5000   False
..    ...      ...     ...
71   21.0   7.8958   False
106  21.0   7.8208   False
270  46.0  75.2417   False
348  24.0  13.5000   False
102   NaN   7.7500    True

[334 rows x 3 columns]

In [19]:
X_test['Age_NA'] = X_test_missing

<ipython-input-19-7d3a75ed3eb3>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['Age_NA'] = X_test_missing


In [20]:
X_test

Age      Fare  Age_NA
321  25.0    7.2292   False
324  39.0  211.3375   False
388  21.0    7.7500   False
56   35.0    7.8958   False
153  36.0   12.1833   False
..    ...       ...     ...
57   25.0    7.6500   False
126  22.0    7.7958   False
24   48.0  262.3750   False
17   21.0    7.2250   False
66   18.0    7.8792   False

[84 rows x 3 columns]

In [21]:
si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [22]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf2,y_train)

y_pred = clf.predict(X_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6071428571428571

In [23]:
si = SimpleImputer(add_indicator=True)

In [24]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [25]:
X_train = si.fit_transform(X_train)

In [26]:
X_test = si.transform(X_test)

In [27]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf2,y_train)

y_pred = clf.predict(X_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6071428571428571